training:
  model:
    model_name: "model_trainable_inputs"
    using_blocs: False
  dataloader:
    folder_path: "prompts/your_directory/"
    truncate_n_prompts: null
    truncate_embds_topk: 1000
    add_property_is_the_same: True
    normalize: "MAX_MIN"
    num_workers: 1
    simulated:
      simulated: False
      dim_clip_simulated: 100
  training:
    n_epochs: 1
    print_frequency: 1
    save_model_frequency: null
    plot_frequency: 1
    seed: 0
    batch_size: 16
    lr: 0.001
    beta1: 0.9
    beta2: 0.999
    lr_scheduler:
      lr_scheduler_type: LINEAR
      lr_scheduler_linear:
        lr_scheduler_lr_final_linear: 0.0001
  sparse_feature_design:
    n_repeat: 10
